sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
# keep the npm cache to speed up installs
cache:
  directories:
    - '$HOME/.npm'

script:
  - yarn global add codecov
  - yarn test

after_success:
  - codecov
